### ISSUE TITLE
Instance Labels

### ISSUE THREAD

**Issue by ScottGuymer** [philips-labs/variant#2]
When labelling an instance for prometheus it should use the instance ID from CF as the id so we can tell apart different instances of apps from with in CF

**Comment by loafoe** [comment]
I'm looking into making this configurable using an annotation. That should provide additional flexibility e.g. in your standard app module you can use `org-space-app`. Version `0.0.12` should have the first attempt. It's a bit trickier for auto-discovering targets where an `index` should be added. Once it works for single instance scrape targets I'll look into supporting service discovered instances.

**Comment by ScottGuymer** [comment]
Why not just use the GUID from CF here? It makes sense that I want to see the metrics for individual instances of apps and not have different instances confused over time.

**Comment by loafoe** [comment]
With the implementation done in 3adb8560478b509360a98cc61cbf6e3263c551d6 and using `prometheus.exporter.instance_name` annotation you can inject the `GUID` or any other identifier as part of the annotation config. The only requirement is that it results stable / predictable `instance` names across deployments.

**Comment by ScottGuymer** [comment]
But the guid for each instance is generted by the CF platform and isnt something available at deploy time. 

This is something distinct from the app guid and identifies each individual instance of an app.

**Comment by loafoe** [comment]
Using instance guids will increase the cardinality of the `instance` label a lot e.g. new values after every deploy, which happens at least once a month to every app instance triggered by our CF upgrade cycle. I would not even recommend using the app `GUID`, but rather a more human friendly naming scheme. But maybe I'm missing the value it woud add?

**Comment by ScottGuymer** [comment]
You need to be able to distinguish between instances to understand if problems are at an app level or instance level. 

For instance 
- trying to understand how the load is being balanced over your instances well
- debugging memory issues to see if they are coming from specific instances

When using Prometheus in k8s you usually have the pod name which is unique to that instance of the pod.

**Comment by loafoe** [comment]
You can use the `index` for this. In the above example, if I wanted to examine / debug the last instance:

```shell
cf target -o hsdp-demo-org -s test
cf ssh kong-e137cd34 -i 3
```

**Comment by ScottGuymer** [comment]
over time this will be changed to a different actual instance though correct?

Say some random instances keep failing and recycling, a new instance should pop up in its place with a new instance ID but it would have the same index. It would then become difficult to see that these were actually different things over time.

**Comment by loafoe** [comment]
Yes, but similar to kubernetes pods, these instances are ephemeral, they come and go, you can't post mortem  them once they have died and have been replaced. 

So the instance guid is only usable during the lifetime of the pod /instance and in that context the index equivalent. In fact, the index is more useful as that is exactly what `cf ssh` expects as param to target the right instance. If you start with  the `guid` you would still need look up the index!

**Comment by loafoe** [comment]
closing as instance index is the higher level abstraction that CF provides and uses for targeting "pods" (in k8s speak)
